# Exercise 1.A NumPy: Manipulating Arrays 


## Looping Through Arrays

In [1]:
import numpy as np

In [12]:
arrA = np.array([
    [11, 12, 13],
    [14,15,16]
                ])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [20]:
for x in arrA:  #Loop through first dimension
    print(x * 2)

[22 24 26]
[28 30 32]


In [26]:
for x in arrA:    #loop through second dimension
    for y in x:
        print (y * 2)

22
24
26
28
30
32


## The main difference I notice for this example is that in the first loop, the numbers are grouped together in brackets, seperated by commas. The second loop just looks like a list of numbers.

In [25]:
loop_result = x * 2 #loop through second dimension with x * 2

for x in arrA:
    for y in x:
        loop_result = x * 2
        print (loop_result)  #The main difference that I notice with this script is that the x * 2 doubles the whole row where as y * 2 doubles one number itself.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [4]:
import numpy as np


In [7]:
arrA = np.array([[11,12,13],
                [14,15,16]])

In [8]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0) #axis = 0
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [10]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1) #axis = 1
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [20]:
another_joined_array = np.concatenate((joined_array_1, arrA, axis==0))   #Error happened because axis = 1 needs both arrays 
print(another_joined_array)

NameError: name 'axis' is not defined

In [19]:
print(arrA.shape)
print(joined_array_1.shape)

(2, 3)
(2, 6)


In [37]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis=0)  #Error happened because axis = 0. When trying to concatenate an array on a default axis the columns must match. 
print(another_joined_array)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

In [36]:
another_2 = np.concatenate((joined_array_1, arrA), axis = 1) #This was able to run when the axis=1 because both arrays have the same amount of rows. 
print(another_2)

[[11 12 13 11 12 13 11 12 13]
 [14 15 16 14 15 16 14 15 16]]


In [42]:
code_red = np.vstack((arrA,arrA)) #Stacks arrays on top eachother
print(code_red)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [43]:
code_black = np.hstack((arrA,arrA)) #Stacks arrays side by side
print(code_black)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [44]:
code_purple = np.dstack((arrA,arrA)) #Stacks arrays in 3 dimensions.
print(code_purple)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [45]:
splitsky = joined_array_1

In [46]:
np.array_split(splitsky,2) #This script gives 2 arrays with 2 dimensions in each.
print(np.array_split(splitsky,2))

[array([[11, 12, 13, 11, 12, 13]]), array([[14, 15, 16, 14, 15, 16]])]


In [47]:
spliterino = joined_array_1

In [48]:
print(np.array_split(spliterino,3)) #This script gives 3 arrays with 2 dimensions each however the third array is empty.

[array([[11, 12, 13, 11, 12, 13]]), array([[14, 15, 16, 14, 15, 16]]), array([], shape=(0, 6), dtype=int64)]


## Searching and Replacing Array Values

In [49]:
import numpy as np

In [50]:
print(arrA)

[[11 12 13]
 [14 15 16]]


In [55]:
result_1 = np.where(arrA % 2 ==0, arrA, 'odd') 
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Array Values.

In [57]:
import numpy as np

In [62]:
arrB = np.array([ #Create variable 
    [7,6],
    [13,5],
    [7,3]
])
print(arrB)
    

[[ 7  6]
 [13  5]
 [ 7  3]]


In [64]:
arrB_sorted = np.sort(arrB) #Sorted
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [65]:
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [67]:
z = arrB < 7
arrC = arrB[z]
print(arrC)

[6 5 3]


In [69]:
z = arrB >= 7
arrD = arrB[z]
print(arrD)

[ 7 13  7]
