In [2]:
import numpy as np 

## Generating Random Numbers

In [2]:
r_1 = np.array([4,12]) 
print(r_1)

[ 4 12]


In [5]:
r_1 = np.random.randint(1,20,2)
print(r_1)

[15 14]


In [13]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.01838823]
 [0.06442228]]


In [3]:
import numpy as np

In [5]:
r_4 = np.random.randint(20,100,(4,5))
print(r_4)

[[33 93 86 28 28]
 [27 49 84 61 62]
 [20 64 56 49 53]
 [96 96 83 25 25]]


In [6]:
r_5 = np.random.randint(4,5)
print(r_5)

4


 ## Generating Random Choices from an array

In [11]:
students = np.array ([
    "naomi", "victoria", "luis", "jennifer",
    "smaya", "joseph", "carter", "june",
    "elias", "frank", "hector", "jose"
])

print(students)

['naomi' 'victoria' 'luis' 'jennifer' 'smaya' 'joseph' 'carter' 'june'
 'elias' 'frank' 'hector' 'jose']


In [17]:
call_on = np.random.choice(students)
print(call_on)

carter


In [21]:
breakout_groups = np.random.choice(students,(3,4)) #This wouldnt be a good way to create breakout rooms because some of these names are duplicated and its not possible for one person to be in two breakout rooms.
print(breakout_groups)

[['frank' 'victoria' 'hector' 'naomi']
 ['jose' 'hector' 'joseph' 'naomi']
 ['jose' 'carter' 'jennifer' 'carter']]


In [ ]:
call_on_weighted = np.random.choice(
    students,
    5,
    p=[0.30,0.10,0.10,0.05,0.05,0.1,0.00,0.05,0.05,0.05, .1,.05]
)
print(call_on_weighted)

## Generating a normal distribution


In [3]:
bell_curve = np.random.normal(10, 5, (4,5))
print(bell_curve)

[[11.71831184  9.62807155 11.9824464  14.01866844 12.70222061]
 [ 7.4352492   0.7376777   6.06893266 14.47600155 13.86947463]
 [ 5.18930104 13.51477861  1.08413349  1.10765284 18.34033491]
 [ 2.79288098 14.27800414 13.55908987  9.49056649  8.52232507]]
